### ISSUE TITLE
Inconsistencies with the spelling of 'AuqaCSS' 

### ISSUE THREAD

**Issue by MystPi** [Darth-Ness/AquaCSS#1]
In the README, you spell 'AuqaCSS' like 'AquaCSS' quite a few times. You should probably fix those misspellings to avoid confusion, or simply rename the repo AquaCSS as it makes more sense.

**Comment by Darth-Ness** [comment]
Thanks for pointing, this out. I'll switch all occurrences of the word "AuqaCSS to "AquaCSS" after dinner.

**Comment by MystPi** [comment]
> Thanks for pointing, this out. I'll switch all occurrences of the word "AuqaCSS to "AquaCSS" after dinner.

I'll make a PR if that's okay, as I already started on one.
