### ISSUE TITLE
"system-ui" is misspelled

### ISSUE THREAD

**Issue by cocoelacanth** [Darth-Ness/AquaCSS#4]
In [AquaMain.css](https://github.com/Darth-Ness/AquaCSS/blob/master/themes/AquaMain.css), the "system-ui" font family is misspelled as "sytem-ui."

Consequently, the entire page uses the browser's default font as opposed to the system font. On a Windows machine, this font is typically Times New Roman, which looks rather out of place here.

![image](https://user-images.githubusercontent.com/44563370/147046208-c8ff98ab-d167-4d35-8a16-31ae56399c23.png)

By contrast, the system font (Segoe UI, in the case of Windows 11) fits in much better with the overall appearance of the website.

![image](https://user-images.githubusercontent.com/44563370/147046248-b94d1b2c-9fb9-48d6-b92a-bbbd471c3f5a.png)

**Comment by Darth-Ness** [comment]
Will be fixed in the next commit.

**Comment by cocoelacanth** [comment]
Misspelling still exists as of 8dbd1db.
